version: '3.9'

services:
  postgres:
    image: postgres:13
    container_name: nova_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: {DB_USERNAME}
      POSTGRES_PASSWORD: {DB_PASSWORD}
      POSTGRES_DB: {DB_NAME}

    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: